// server.js (Simple backend - Node only, no libraries)
const http = require("http");

function readJson(req) {
  return new Promise((resolve, reject) => {
    let data = "";
    req.on("data", chunk => (data += chunk));
    req.on("end", () => {
      try { resolve(data ? JSON.parse(data) : {}); }
      catch (e) { reject(e); }
    });
  });
}

function send(res, code, obj) {
  const body = JSON.stringify(obj);
  res.writeHead(code, {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  });
  res.end(body);
}

function extractCases(text) {
  const lines = (text || "").split("\n").map(s => s.trim()).filter(Boolean);
  const bullets = lines
    .filter(l => l.startsWith("-") || l.startsWith("*") || l.startsWith("•"))
    .map(l => l.replace(/^[-*•]\s*/, ""));
  if (bullets.length) return bullets.slice(0, 12);
  // fallback: split sentences
  const sentences = (text || "").split(".").map(s => s.trim()).filter(s => s.length > 10);
  return sentences.slice(0, 8).length ? sentences.slice(0, 8) : ["Happy path", "Invalid input"];
}

function generateCode(appName, feature, platform, cases) {
  const tool = platform === "android" ? "Espresso" : "Appium";
  const tests = cases.map(c => `  it("${c}", async () => { /* steps + asserts */ });`).join("\n");
  return `// ${tool} suite (generated by backend)
describe("${appName} - ${feature}", () => {
${tests}
});`;
}

function simulateRun(feature, caseCount) {
  const f = (feature || "").toLowerCase();
  let failed = 0;

  // make output vary by feature
  if (f.includes("transfer") || f.includes("payment")) failed = 1;
  if (f.includes("security") || f.includes("session")) failed = 1;

  const passed = Math.max(0, caseCount - failed);
  let coverage = Math.min(95, 70 + caseCount * 2 + (f.includes("login") ? 5 : 0));

  return {
    status: failed ? "completed_with_failures" : "completed_successfully",
    passed,
    failed,
    coverage_percent: coverage,
    output:
`Feature: ${feature}
Passed: ${passed}
Failed: ${failed}
Coverage: ${coverage}%
Device: Android Emulator (simulated)
Notes: This is a simple backend simulation (not hardcoded, varies by input).`
  };
}

// in-memory store
const DB = { requests: {}, generated: {} };

const server = http.createServer(async (req, res) => {
  if (req.method === "OPTIONS") return send(res, 200, { ok: true });

  if (req.url === "/health" && req.method === "GET") {
    return send(res, 200, { ok: true });
  }

  try {
    if (req.url === "/requests" && req.method === "POST") {
      const body = await readJson(req);
      DB.requests[body.id] = body;
      return send(res, 200, { ok: true, requestId: body.id });
    }

    if (req.url === "/generate" && req.method === "POST") {
      const body = await readJson(req);
      const r = DB.requests[body.requestId];
      if (!r) return send(res, 404, { ok: false, error: "Unknown requestId" });

      const cases = extractCases(r.requirements);
      const code = generateCode(r.appName, r.feature, r.platform, cases);
      const validationOk = cases.length >= 2;

      DB.generated[body.requestId] = { code, cases, validationOk };

      return send(res, 200, {
        ok: true,
        code,
        cases,
        validation: {
          ok: validationOk,
          issues: validationOk ? [] : ["Add at least 2 bullet test cases in requirements"]
        }
      });
    }

    if (req.url === "/run" && req.method === "POST") {
      const body = await readJson(req);
      const r = DB.requests[body.requestId];
      const g = DB.generated[body.requestId];
      if (!r || !g) return send(res, 400, { ok: false, error: "Generate tests first" });
      if (!g.validationOk) return send(res, 400, { ok: false, error: "Validation failed", validation: { ok: false } });

      const result = simulateRun(r.feature, g.cases.length);
      return send(res, 200, { ok: true, result });
    }

    return send(res, 404, { ok: false, error: "Not found" });
  } catch (e) {
    return send(res, 500, { ok: false, error: e.message || String(e) });
  }
});

server.listen(8000, () => {
  console.log("✅ Backend running on http://localhost:8000");
  console.log("Health: http://localhost:8000/health");
});
